version: "3"

services:
  redis:
    image: redis:7.0.2-alpine3.16
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/data/:/data
      - ./db-conf:/usr/local/etc/redis
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - ./db-data/redisinsight:/db
